// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CinemaGateway_GetShowtimeWithMovie_FullMethodName    = "/gateway.CinemaGateway/GetShowtimeWithMovie"
	CinemaGateway_SendBookingNotification_FullMethodName = "/gateway.CinemaGateway/SendBookingNotification"
	CinemaGateway_GetBookingDetails_FullMethodName       = "/gateway.CinemaGateway/GetBookingDetails"
)

// CinemaGatewayClient is the client API for CinemaGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CinemaGatewayClient interface {
	GetShowtimeWithMovie(ctx context.Context, in *GetShowtimeWithMovieRequest, opts ...grpc.CallOption) (*ShowtimeWithMovie, error)
	SendBookingNotification(ctx context.Context, in *SendBookingNotificationRequest, opts ...grpc.CallOption) (*SendBookingNotificationResponse, error)
	GetBookingDetails(ctx context.Context, in *GetBookingDetailsRequest, opts ...grpc.CallOption) (*BookingDetails, error)
}

type cinemaGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewCinemaGatewayClient(cc grpc.ClientConnInterface) CinemaGatewayClient {
	return &cinemaGatewayClient{cc}
}

func (c *cinemaGatewayClient) GetShowtimeWithMovie(ctx context.Context, in *GetShowtimeWithMovieRequest, opts ...grpc.CallOption) (*ShowtimeWithMovie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowtimeWithMovie)
	err := c.cc.Invoke(ctx, CinemaGateway_GetShowtimeWithMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaGatewayClient) SendBookingNotification(ctx context.Context, in *SendBookingNotificationRequest, opts ...grpc.CallOption) (*SendBookingNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBookingNotificationResponse)
	err := c.cc.Invoke(ctx, CinemaGateway_SendBookingNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaGatewayClient) GetBookingDetails(ctx context.Context, in *GetBookingDetailsRequest, opts ...grpc.CallOption) (*BookingDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingDetails)
	err := c.cc.Invoke(ctx, CinemaGateway_GetBookingDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CinemaGatewayServer is the server API for CinemaGateway service.
// All implementations must embed UnimplementedCinemaGatewayServer
// for forward compatibility.
type CinemaGatewayServer interface {
	GetShowtimeWithMovie(context.Context, *GetShowtimeWithMovieRequest) (*ShowtimeWithMovie, error)
	SendBookingNotification(context.Context, *SendBookingNotificationRequest) (*SendBookingNotificationResponse, error)
	GetBookingDetails(context.Context, *GetBookingDetailsRequest) (*BookingDetails, error)
	mustEmbedUnimplementedCinemaGatewayServer()
}

// UnimplementedCinemaGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCinemaGatewayServer struct{}

func (UnimplementedCinemaGatewayServer) GetShowtimeWithMovie(context.Context, *GetShowtimeWithMovieRequest) (*ShowtimeWithMovie, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShowtimeWithMovie not implemented")
}
func (UnimplementedCinemaGatewayServer) SendBookingNotification(context.Context, *SendBookingNotificationRequest) (*SendBookingNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBookingNotification not implemented")
}
func (UnimplementedCinemaGatewayServer) GetBookingDetails(context.Context, *GetBookingDetailsRequest) (*BookingDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookingDetails not implemented")
}
func (UnimplementedCinemaGatewayServer) mustEmbedUnimplementedCinemaGatewayServer() {}
func (UnimplementedCinemaGatewayServer) testEmbeddedByValue()                       {}

// UnsafeCinemaGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CinemaGatewayServer will
// result in compilation errors.
type UnsafeCinemaGatewayServer interface {
	mustEmbedUnimplementedCinemaGatewayServer()
}

func RegisterCinemaGatewayServer(s grpc.ServiceRegistrar, srv CinemaGatewayServer) {
	// If the following call panics, it indicates UnimplementedCinemaGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CinemaGateway_ServiceDesc, srv)
}

func _CinemaGateway_GetShowtimeWithMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowtimeWithMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaGatewayServer).GetShowtimeWithMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CinemaGateway_GetShowtimeWithMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaGatewayServer).GetShowtimeWithMovie(ctx, req.(*GetShowtimeWithMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CinemaGateway_SendBookingNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBookingNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaGatewayServer).SendBookingNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CinemaGateway_SendBookingNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaGatewayServer).SendBookingNotification(ctx, req.(*SendBookingNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CinemaGateway_GetBookingDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaGatewayServer).GetBookingDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CinemaGateway_GetBookingDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaGatewayServer).GetBookingDetails(ctx, req.(*GetBookingDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CinemaGateway_ServiceDesc is the grpc.ServiceDesc for CinemaGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CinemaGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.CinemaGateway",
	HandlerType: (*CinemaGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShowtimeWithMovie",
			Handler:    _CinemaGateway_GetShowtimeWithMovie_Handler,
		},
		{
			MethodName: "SendBookingNotification",
			Handler:    _CinemaGateway_SendBookingNotification_Handler,
		},
		{
			MethodName: "GetBookingDetails",
			Handler:    _CinemaGateway_GetBookingDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
