// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShowtimeWithMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    string                 `protobuf:"bytes,1,opt,name=showtime_id,json=showtimeId,proto3" json:"showtime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeWithMovieRequest) Reset() {
	*x = GetShowtimeWithMovieRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeWithMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeWithMovieRequest) ProtoMessage() {}

func (x *GetShowtimeWithMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeWithMovieRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimeWithMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetShowtimeWithMovieRequest) GetShowtimeId() string {
	if x != nil {
		return x.ShowtimeId
	}
	return ""
}

type ShowtimeWithMovie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    string                 `protobuf:"bytes,1,opt,name=showtime_id,json=showtimeId,proto3" json:"showtime_id,omitempty"`
	MovieTitle    string                 `protobuf:"bytes,2,opt,name=movie_title,json=movieTitle,proto3" json:"movie_title,omitempty"`
	Hall          string                 `protobuf:"bytes,3,opt,name=hall,proto3" json:"hall,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowtimeWithMovie) Reset() {
	*x = ShowtimeWithMovie{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowtimeWithMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowtimeWithMovie) ProtoMessage() {}

func (x *ShowtimeWithMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowtimeWithMovie.ProtoReflect.Descriptor instead.
func (*ShowtimeWithMovie) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ShowtimeWithMovie) GetShowtimeId() string {
	if x != nil {
		return x.ShowtimeId
	}
	return ""
}

func (x *ShowtimeWithMovie) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

func (x *ShowtimeWithMovie) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *ShowtimeWithMovie) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type SendBookingNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BookingId      string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RecipientEmail string                 `protobuf:"bytes,2,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBookingNotificationRequest) Reset() {
	*x = SendBookingNotificationRequest{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingNotificationRequest) ProtoMessage() {}

func (x *SendBookingNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBookingNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendBookingNotificationRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SendBookingNotificationRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

type SendBookingNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingNotificationResponse) Reset() {
	*x = SendBookingNotificationResponse{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingNotificationResponse) ProtoMessage() {}

func (x *SendBookingNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendBookingNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SendBookingNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBookingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingDetailsRequest) Reset() {
	*x = GetBookingDetailsRequest{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingDetailsRequest) ProtoMessage() {}

func (x *GetBookingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingDetailsRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type BookingDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieTitle    string                 `protobuf:"bytes,3,opt,name=movie_title,json=movieTitle,proto3" json:"movie_title,omitempty"`
	Hall          string                 `protobuf:"bytes,4,opt,name=hall,proto3" json:"hall,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Seats         []string               `protobuf:"bytes,6,rep,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingDetails) Reset() {
	*x = BookingDetails{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetails) ProtoMessage() {}

func (x *BookingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetails.ProtoReflect.Descriptor instead.
func (*BookingDetails) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *BookingDetails) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingDetails) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

func (x *BookingDetails) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *BookingDetails) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BookingDetails) GetSeats() []string {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *BookingDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\">\n" +
	"\x1bGetShowtimeWithMovieRequest\x12\x1f\n" +
	"\vshowtime_id\x18\x01 \x01(\tR\n" +
	"showtimeId\"\x88\x01\n" +
	"\x11ShowtimeWithMovie\x12\x1f\n" +
	"\vshowtime_id\x18\x01 \x01(\tR\n" +
	"showtimeId\x12\x1f\n" +
	"\vmovie_title\x18\x02 \x01(\tR\n" +
	"movieTitle\x12\x12\n" +
	"\x04hall\x18\x03 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\"h\n" +
	"\x1eSendBookingNotificationRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12'\n" +
	"\x0frecipient_email\x18\x02 \x01(\tR\x0erecipientEmail\";\n" +
	"\x1fSendBookingNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x18GetBookingDetailsRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"\xca\x01\n" +
	"\x0eBookingDetails\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmovie_title\x18\x03 \x01(\tR\n" +
	"movieTitle\x12\x12\n" +
	"\x04hall\x18\x04 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x14\n" +
	"\x05seats\x18\x06 \x03(\tR\x05seats\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status2\xa8\x02\n" +
	"\rCinemaGateway\x12X\n" +
	"\x14GetShowtimeWithMovie\x12$.gateway.GetShowtimeWithMovieRequest\x1a\x1a.gateway.ShowtimeWithMovie\x12l\n" +
	"\x17SendBookingNotification\x12'.gateway.SendBookingNotificationRequest\x1a(.gateway.SendBookingNotificationResponse\x12O\n" +
	"\x11GetBookingDetails\x12!.gateway.GetBookingDetailsRequest\x1a\x17.gateway.BookingDetailsB4Z2github.com/cinema-system/api-gateway/proto/gatewayb\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_gateway_proto_goTypes = []any{
	(*GetShowtimeWithMovieRequest)(nil),     // 0: gateway.GetShowtimeWithMovieRequest
	(*ShowtimeWithMovie)(nil),               // 1: gateway.ShowtimeWithMovie
	(*SendBookingNotificationRequest)(nil),  // 2: gateway.SendBookingNotificationRequest
	(*SendBookingNotificationResponse)(nil), // 3: gateway.SendBookingNotificationResponse
	(*GetBookingDetailsRequest)(nil),        // 4: gateway.GetBookingDetailsRequest
	(*BookingDetails)(nil),                  // 5: gateway.BookingDetails
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.CinemaGateway.GetShowtimeWithMovie:input_type -> gateway.GetShowtimeWithMovieRequest
	2, // 1: gateway.CinemaGateway.SendBookingNotification:input_type -> gateway.SendBookingNotificationRequest
	4, // 2: gateway.CinemaGateway.GetBookingDetails:input_type -> gateway.GetBookingDetailsRequest
	1, // 3: gateway.CinemaGateway.GetShowtimeWithMovie:output_type -> gateway.ShowtimeWithMovie
	3, // 4: gateway.CinemaGateway.SendBookingNotification:output_type -> gateway.SendBookingNotificationResponse
	5, // 5: gateway.CinemaGateway.GetBookingDetails:output_type -> gateway.BookingDetails
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
