// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/showtime.proto

package showtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShowtimeService_GetShowtime_FullMethodName          = "/showtime.ShowtimeService/GetShowtime"
	ShowtimeService_ListShowtimesByMovie_FullMethodName = "/showtime.ShowtimeService/ListShowtimesByMovie"
	ShowtimeService_GetSeatAvailability_FullMethodName  = "/showtime.ShowtimeService/GetSeatAvailability"
	ShowtimeService_CreateShowtime_FullMethodName       = "/showtime.ShowtimeService/CreateShowtime"
	ShowtimeService_UpdateShowtime_FullMethodName       = "/showtime.ShowtimeService/UpdateShowtime"
	ShowtimeService_DeleteShowtime_FullMethodName       = "/showtime.ShowtimeService/DeleteShowtime"
)

// ShowtimeServiceClient is the client API for ShowtimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowtimeServiceClient interface {
	GetShowtime(ctx context.Context, in *GetShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error)
	ListShowtimesByMovie(ctx context.Context, in *ListShowtimesByMovieRequest, opts ...grpc.CallOption) (*ListShowtimesResponse, error)
	GetSeatAvailability(ctx context.Context, in *GetSeatAvailabilityRequest, opts ...grpc.CallOption) (*SeatAvailabilityResponse, error)
	CreateShowtime(ctx context.Context, in *CreateShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error)
	UpdateShowtime(ctx context.Context, in *UpdateShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error)
	DeleteShowtime(ctx context.Context, in *DeleteShowtimeRequest, opts ...grpc.CallOption) (*DeleteShowtimeResponse, error)
}

type showtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowtimeServiceClient(cc grpc.ClientConnInterface) ShowtimeServiceClient {
	return &showtimeServiceClient{cc}
}

func (c *showtimeServiceClient) GetShowtime(ctx context.Context, in *GetShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Showtime)
	err := c.cc.Invoke(ctx, ShowtimeService_GetShowtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeServiceClient) ListShowtimesByMovie(ctx context.Context, in *ListShowtimesByMovieRequest, opts ...grpc.CallOption) (*ListShowtimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShowtimesResponse)
	err := c.cc.Invoke(ctx, ShowtimeService_ListShowtimesByMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeServiceClient) GetSeatAvailability(ctx context.Context, in *GetSeatAvailabilityRequest, opts ...grpc.CallOption) (*SeatAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatAvailabilityResponse)
	err := c.cc.Invoke(ctx, ShowtimeService_GetSeatAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeServiceClient) CreateShowtime(ctx context.Context, in *CreateShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Showtime)
	err := c.cc.Invoke(ctx, ShowtimeService_CreateShowtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeServiceClient) UpdateShowtime(ctx context.Context, in *UpdateShowtimeRequest, opts ...grpc.CallOption) (*Showtime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Showtime)
	err := c.cc.Invoke(ctx, ShowtimeService_UpdateShowtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showtimeServiceClient) DeleteShowtime(ctx context.Context, in *DeleteShowtimeRequest, opts ...grpc.CallOption) (*DeleteShowtimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShowtimeResponse)
	err := c.cc.Invoke(ctx, ShowtimeService_DeleteShowtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowtimeServiceServer is the server API for ShowtimeService service.
// All implementations must embed UnimplementedShowtimeServiceServer
// for forward compatibility.
type ShowtimeServiceServer interface {
	GetShowtime(context.Context, *GetShowtimeRequest) (*Showtime, error)
	ListShowtimesByMovie(context.Context, *ListShowtimesByMovieRequest) (*ListShowtimesResponse, error)
	GetSeatAvailability(context.Context, *GetSeatAvailabilityRequest) (*SeatAvailabilityResponse, error)
	CreateShowtime(context.Context, *CreateShowtimeRequest) (*Showtime, error)
	UpdateShowtime(context.Context, *UpdateShowtimeRequest) (*Showtime, error)
	DeleteShowtime(context.Context, *DeleteShowtimeRequest) (*DeleteShowtimeResponse, error)
	mustEmbedUnimplementedShowtimeServiceServer()
}

// UnimplementedShowtimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShowtimeServiceServer struct{}

func (UnimplementedShowtimeServiceServer) GetShowtime(context.Context, *GetShowtimeRequest) (*Showtime, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShowtime not implemented")
}
func (UnimplementedShowtimeServiceServer) ListShowtimesByMovie(context.Context, *ListShowtimesByMovieRequest) (*ListShowtimesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShowtimesByMovie not implemented")
}
func (UnimplementedShowtimeServiceServer) GetSeatAvailability(context.Context, *GetSeatAvailabilityRequest) (*SeatAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatAvailability not implemented")
}
func (UnimplementedShowtimeServiceServer) CreateShowtime(context.Context, *CreateShowtimeRequest) (*Showtime, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShowtime not implemented")
}
func (UnimplementedShowtimeServiceServer) UpdateShowtime(context.Context, *UpdateShowtimeRequest) (*Showtime, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShowtime not implemented")
}
func (UnimplementedShowtimeServiceServer) DeleteShowtime(context.Context, *DeleteShowtimeRequest) (*DeleteShowtimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShowtime not implemented")
}
func (UnimplementedShowtimeServiceServer) mustEmbedUnimplementedShowtimeServiceServer() {}
func (UnimplementedShowtimeServiceServer) testEmbeddedByValue()                         {}

// UnsafeShowtimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowtimeServiceServer will
// result in compilation errors.
type UnsafeShowtimeServiceServer interface {
	mustEmbedUnimplementedShowtimeServiceServer()
}

func RegisterShowtimeServiceServer(s grpc.ServiceRegistrar, srv ShowtimeServiceServer) {
	// If the following call panics, it indicates UnimplementedShowtimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShowtimeService_ServiceDesc, srv)
}

func _ShowtimeService_GetShowtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).GetShowtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_GetShowtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).GetShowtime(ctx, req.(*GetShowtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShowtimeService_ListShowtimesByMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShowtimesByMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).ListShowtimesByMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_ListShowtimesByMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).ListShowtimesByMovie(ctx, req.(*ListShowtimesByMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShowtimeService_GetSeatAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).GetSeatAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_GetSeatAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).GetSeatAvailability(ctx, req.(*GetSeatAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShowtimeService_CreateShowtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShowtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).CreateShowtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_CreateShowtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).CreateShowtime(ctx, req.(*CreateShowtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShowtimeService_UpdateShowtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShowtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).UpdateShowtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_UpdateShowtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).UpdateShowtime(ctx, req.(*UpdateShowtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShowtimeService_DeleteShowtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShowtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowtimeServiceServer).DeleteShowtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowtimeService_DeleteShowtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowtimeServiceServer).DeleteShowtime(ctx, req.(*DeleteShowtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShowtimeService_ServiceDesc is the grpc.ServiceDesc for ShowtimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShowtimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "showtime.ShowtimeService",
	HandlerType: (*ShowtimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShowtime",
			Handler:    _ShowtimeService_GetShowtime_Handler,
		},
		{
			MethodName: "ListShowtimesByMovie",
			Handler:    _ShowtimeService_ListShowtimesByMovie_Handler,
		},
		{
			MethodName: "GetSeatAvailability",
			Handler:    _ShowtimeService_GetSeatAvailability_Handler,
		},
		{
			MethodName: "CreateShowtime",
			Handler:    _ShowtimeService_CreateShowtime_Handler,
		},
		{
			MethodName: "UpdateShowtime",
			Handler:    _ShowtimeService_UpdateShowtime_Handler,
		},
		{
			MethodName: "DeleteShowtime",
			Handler:    _ShowtimeService_DeleteShowtime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/showtime.proto",
}
