// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/showtime.proto

package showtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Showtime struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId        string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Hall           string                 `protobuf:"bytes,3,opt,name=hall,proto3" json:"hall,omitempty"`
	StartTime      string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,5,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Showtime) Reset() {
	*x = Showtime{}
	mi := &file_proto_showtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Showtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Showtime) ProtoMessage() {}

func (x *Showtime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Showtime.ProtoReflect.Descriptor instead.
func (*Showtime) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{0}
}

func (x *Showtime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Showtime) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Showtime) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *Showtime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Showtime) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type GetShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowtimeRequest) Reset() {
	*x = GetShowtimeRequest{}
	mi := &file_proto_showtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowtimeRequest) ProtoMessage() {}

func (x *GetShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowtimeRequest.ProtoReflect.Descriptor instead.
func (*GetShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{1}
}

func (x *GetShowtimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListShowtimesByMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesByMovieRequest) Reset() {
	*x = ListShowtimesByMovieRequest{}
	mi := &file_proto_showtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesByMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesByMovieRequest) ProtoMessage() {}

func (x *ListShowtimesByMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesByMovieRequest.ProtoReflect.Descriptor instead.
func (*ListShowtimesByMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{2}
}

func (x *ListShowtimesByMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type ListShowtimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Showtimes     []*Showtime            `protobuf:"bytes,1,rep,name=showtimes,proto3" json:"showtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowtimesResponse) Reset() {
	*x = ListShowtimesResponse{}
	mi := &file_proto_showtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowtimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowtimesResponse) ProtoMessage() {}

func (x *ListShowtimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowtimesResponse.ProtoReflect.Descriptor instead.
func (*ListShowtimesResponse) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{3}
}

func (x *ListShowtimesResponse) GetShowtimes() []*Showtime {
	if x != nil {
		return x.Showtimes
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Row           string                 `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,4,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_showtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{4}
}

func (x *Seat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seat) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *Seat) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Seat) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type GetSeatAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    string                 `protobuf:"bytes,1,opt,name=showtime_id,json=showtimeId,proto3" json:"showtime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatAvailabilityRequest) Reset() {
	*x = GetSeatAvailabilityRequest{}
	mi := &file_proto_showtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatAvailabilityRequest) ProtoMessage() {}

func (x *GetSeatAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetSeatAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeatAvailabilityRequest) GetShowtimeId() string {
	if x != nil {
		return x.ShowtimeId
	}
	return ""
}

type SeatAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatAvailabilityResponse) Reset() {
	*x = SeatAvailabilityResponse{}
	mi := &file_proto_showtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatAvailabilityResponse) ProtoMessage() {}

func (x *SeatAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*SeatAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{6}
}

func (x *SeatAvailabilityResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type CreateShowtimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MovieId        string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Hall           string                 `protobuf:"bytes,2,opt,name=hall,proto3" json:"hall,omitempty"`
	StartTime      string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,4,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShowtimeRequest) Reset() {
	*x = CreateShowtimeRequest{}
	mi := &file_proto_showtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowtimeRequest) ProtoMessage() {}

func (x *CreateShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowtimeRequest.ProtoReflect.Descriptor instead.
func (*CreateShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShowtimeRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *CreateShowtimeRequest) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *CreateShowtimeRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateShowtimeRequest) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type UpdateShowtimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId        string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Hall           string                 `protobuf:"bytes,3,opt,name=hall,proto3" json:"hall,omitempty"`
	StartTime      string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,5,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShowtimeRequest) Reset() {
	*x = UpdateShowtimeRequest{}
	mi := &file_proto_showtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowtimeRequest) ProtoMessage() {}

func (x *UpdateShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowtimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShowtimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShowtimeRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *UpdateShowtimeRequest) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *UpdateShowtimeRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateShowtimeRequest) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type DeleteShowtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowtimeRequest) Reset() {
	*x = DeleteShowtimeRequest{}
	mi := &file_proto_showtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowtimeRequest) ProtoMessage() {}

func (x *DeleteShowtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowtimeRequest.ProtoReflect.Descriptor instead.
func (*DeleteShowtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShowtimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteShowtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowtimeResponse) Reset() {
	*x = DeleteShowtimeResponse{}
	mi := &file_proto_showtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowtimeResponse) ProtoMessage() {}

func (x *DeleteShowtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_showtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowtimeResponse.ProtoReflect.Descriptor instead.
func (*DeleteShowtimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_showtime_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShowtimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_showtime_proto protoreflect.FileDescriptor

const file_proto_showtime_proto_rawDesc = "" +
	"\n" +
	"\x14proto/showtime.proto\x12\bshowtime\"\x91\x01\n" +
	"\bShowtime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x12\n" +
	"\x04hall\x18\x03 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12'\n" +
	"\x0favailable_seats\x18\x05 \x01(\x05R\x0eavailableSeats\"$\n" +
	"\x12GetShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x1bListShowtimesByMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"I\n" +
	"\x15ListShowtimesResponse\x120\n" +
	"\tshowtimes\x18\x01 \x03(\v2\x12.showtime.ShowtimeR\tshowtimes\"c\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03row\x18\x02 \x01(\tR\x03row\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12!\n" +
	"\fis_available\x18\x04 \x01(\bR\visAvailable\"=\n" +
	"\x1aGetSeatAvailabilityRequest\x12\x1f\n" +
	"\vshowtime_id\x18\x01 \x01(\tR\n" +
	"showtimeId\"@\n" +
	"\x18SeatAvailabilityResponse\x12$\n" +
	"\x05seats\x18\x01 \x03(\v2\x0e.showtime.SeatR\x05seats\"\x8e\x01\n" +
	"\x15CreateShowtimeRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x12\n" +
	"\x04hall\x18\x02 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12'\n" +
	"\x0favailable_seats\x18\x04 \x01(\x05R\x0eavailableSeats\"\x9e\x01\n" +
	"\x15UpdateShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x12\n" +
	"\x04hall\x18\x03 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12'\n" +
	"\x0favailable_seats\x18\x05 \x01(\x05R\x0eavailableSeats\"'\n" +
	"\x15DeleteShowtimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteShowtimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf6\x03\n" +
	"\x0fShowtimeService\x12?\n" +
	"\vGetShowtime\x12\x1c.showtime.GetShowtimeRequest\x1a\x12.showtime.Showtime\x12^\n" +
	"\x14ListShowtimesByMovie\x12%.showtime.ListShowtimesByMovieRequest\x1a\x1f.showtime.ListShowtimesResponse\x12_\n" +
	"\x13GetSeatAvailability\x12$.showtime.GetSeatAvailabilityRequest\x1a\".showtime.SeatAvailabilityResponse\x12E\n" +
	"\x0eCreateShowtime\x12\x1f.showtime.CreateShowtimeRequest\x1a\x12.showtime.Showtime\x12E\n" +
	"\x0eUpdateShowtime\x12\x1f.showtime.UpdateShowtimeRequest\x1a\x12.showtime.Showtime\x12S\n" +
	"\x0eDeleteShowtime\x12\x1f.showtime.DeleteShowtimeRequest\x1a .showtime.DeleteShowtimeResponseB:Z8github.com/cinema-system/showtime-service/proto/showtimeb\x06proto3"

var (
	file_proto_showtime_proto_rawDescOnce sync.Once
	file_proto_showtime_proto_rawDescData []byte
)

func file_proto_showtime_proto_rawDescGZIP() []byte {
	file_proto_showtime_proto_rawDescOnce.Do(func() {
		file_proto_showtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_showtime_proto_rawDesc), len(file_proto_showtime_proto_rawDesc)))
	})
	return file_proto_showtime_proto_rawDescData
}

var file_proto_showtime_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_showtime_proto_goTypes = []any{
	(*Showtime)(nil),                    // 0: showtime.Showtime
	(*GetShowtimeRequest)(nil),          // 1: showtime.GetShowtimeRequest
	(*ListShowtimesByMovieRequest)(nil), // 2: showtime.ListShowtimesByMovieRequest
	(*ListShowtimesResponse)(nil),       // 3: showtime.ListShowtimesResponse
	(*Seat)(nil),                        // 4: showtime.Seat
	(*GetSeatAvailabilityRequest)(nil),  // 5: showtime.GetSeatAvailabilityRequest
	(*SeatAvailabilityResponse)(nil),    // 6: showtime.SeatAvailabilityResponse
	(*CreateShowtimeRequest)(nil),       // 7: showtime.CreateShowtimeRequest
	(*UpdateShowtimeRequest)(nil),       // 8: showtime.UpdateShowtimeRequest
	(*DeleteShowtimeRequest)(nil),       // 9: showtime.DeleteShowtimeRequest
	(*DeleteShowtimeResponse)(nil),      // 10: showtime.DeleteShowtimeResponse
}
var file_proto_showtime_proto_depIdxs = []int32{
	0,  // 0: showtime.ListShowtimesResponse.showtimes:type_name -> showtime.Showtime
	4,  // 1: showtime.SeatAvailabilityResponse.seats:type_name -> showtime.Seat
	1,  // 2: showtime.ShowtimeService.GetShowtime:input_type -> showtime.GetShowtimeRequest
	2,  // 3: showtime.ShowtimeService.ListShowtimesByMovie:input_type -> showtime.ListShowtimesByMovieRequest
	5,  // 4: showtime.ShowtimeService.GetSeatAvailability:input_type -> showtime.GetSeatAvailabilityRequest
	7,  // 5: showtime.ShowtimeService.CreateShowtime:input_type -> showtime.CreateShowtimeRequest
	8,  // 6: showtime.ShowtimeService.UpdateShowtime:input_type -> showtime.UpdateShowtimeRequest
	9,  // 7: showtime.ShowtimeService.DeleteShowtime:input_type -> showtime.DeleteShowtimeRequest
	0,  // 8: showtime.ShowtimeService.GetShowtime:output_type -> showtime.Showtime
	3,  // 9: showtime.ShowtimeService.ListShowtimesByMovie:output_type -> showtime.ListShowtimesResponse
	6,  // 10: showtime.ShowtimeService.GetSeatAvailability:output_type -> showtime.SeatAvailabilityResponse
	0,  // 11: showtime.ShowtimeService.CreateShowtime:output_type -> showtime.Showtime
	0,  // 12: showtime.ShowtimeService.UpdateShowtime:output_type -> showtime.Showtime
	10, // 13: showtime.ShowtimeService.DeleteShowtime:output_type -> showtime.DeleteShowtimeResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_showtime_proto_init() }
func file_proto_showtime_proto_init() {
	if File_proto_showtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_showtime_proto_rawDesc), len(file_proto_showtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_showtime_proto_goTypes,
		DependencyIndexes: file_proto_showtime_proto_depIdxs,
		MessageInfos:      file_proto_showtime_proto_msgTypes,
	}.Build()
	File_proto_showtime_proto = out.File
	file_proto_showtime_proto_goTypes = nil
	file_proto_showtime_proto_depIdxs = nil
}
