// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBookingConfirmationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BookingId      string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RecipientEmail string                 `protobuf:"bytes,2,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBookingConfirmationRequest) Reset() {
	*x = SendBookingConfirmationRequest{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingConfirmationRequest) ProtoMessage() {}

func (x *SendBookingConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendBookingConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendBookingConfirmationRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

type SendBookingConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingConfirmationResponse) Reset() {
	*x = SendBookingConfirmationResponse{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingConfirmationResponse) ProtoMessage() {}

func (x *SendBookingConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingConfirmationResponse.ProtoReflect.Descriptor instead.
func (*SendBookingConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendBookingConfirmationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEmailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailLogsRequest) Reset() {
	*x = GetEmailLogsRequest{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailLogsRequest) ProtoMessage() {}

func (x *GetEmailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailLogsRequest.ProtoReflect.Descriptor instead.
func (*GetEmailLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

type EmailLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SentAt        string                 `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLog) Reset() {
	*x = EmailLog{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLog) ProtoMessage() {}

func (x *EmailLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLog.ProtoReflect.Descriptor instead.
func (*EmailLog) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *EmailLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailLog) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *EmailLog) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailLog) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EmailLog) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *EmailLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEmailLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*EmailLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailLogsResponse) Reset() {
	*x = GetEmailLogsResponse{}
	mi := &file_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailLogsResponse) ProtoMessage() {}

func (x *GetEmailLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailLogsResponse.ProtoReflect.Descriptor instead.
func (*GetEmailLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetEmailLogsResponse) GetLogs() []*EmailLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\fnotification\"h\n" +
	"\x1eSendBookingConfirmationRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12'\n" +
	"\x0frecipient_email\x18\x02 \x01(\tR\x0erecipientEmail\";\n" +
	"\x1fSendBookingConfirmationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13GetEmailLogsRequest\"\x97\x01\n" +
	"\bEmailLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\tR\x06sentAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"B\n" +
	"\x14GetEmailLogsResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.notification.EmailLogR\x04logs\"\x14\n" +
	"\x12HealthCheckRequest\"%\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb8\x02\n" +
	"\x13NotificationService\x12v\n" +
	"\x17SendBookingConfirmation\x12,.notification.SendBookingConfirmationRequest\x1a-.notification.SendBookingConfirmationResponse\x12U\n" +
	"\fGetEmailLogs\x12!.notification.GetEmailLogsRequest\x1a\".notification.GetEmailLogsResponse\x12R\n" +
	"\vHealthCheck\x12 .notification.HealthCheckRequest\x1a!.notification.HealthCheckResponseBBZ@github.com/cinema-system/notification-service/proto/notificationb\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_notification_proto_goTypes = []any{
	(*SendBookingConfirmationRequest)(nil),  // 0: notification.SendBookingConfirmationRequest
	(*SendBookingConfirmationResponse)(nil), // 1: notification.SendBookingConfirmationResponse
	(*GetEmailLogsRequest)(nil),             // 2: notification.GetEmailLogsRequest
	(*EmailLog)(nil),                        // 3: notification.EmailLog
	(*GetEmailLogsResponse)(nil),            // 4: notification.GetEmailLogsResponse
	(*HealthCheckRequest)(nil),              // 5: notification.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 6: notification.HealthCheckResponse
}
var file_proto_notification_proto_depIdxs = []int32{
	3, // 0: notification.GetEmailLogsResponse.logs:type_name -> notification.EmailLog
	0, // 1: notification.NotificationService.SendBookingConfirmation:input_type -> notification.SendBookingConfirmationRequest
	2, // 2: notification.NotificationService.GetEmailLogs:input_type -> notification.GetEmailLogsRequest
	5, // 3: notification.NotificationService.HealthCheck:input_type -> notification.HealthCheckRequest
	1, // 4: notification.NotificationService.SendBookingConfirmation:output_type -> notification.SendBookingConfirmationResponse
	4, // 5: notification.NotificationService.GetEmailLogs:output_type -> notification.GetEmailLogsResponse
	6, // 6: notification.NotificationService.HealthCheck:output_type -> notification.HealthCheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
